import Anchor from 'components/Anchor'
import Layout from 'components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import { ArrowRight, Discord } from 'react-bootstrap-icons'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import 'swiper/css/effect-coverflow'
import 'swiper/css/autoplay'
import { Autoplay, EffectCoverflow, Pagination } from 'swiper'
import Heading from 'components/Heading'
import Box from 'components/Box'
import Aos from 'aos'
import { useEffect } from 'react'
import 'aos/dist/aos.css'
import Accordion from 'components/Accordion'

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 1000, once: true })
  }, [])

  return (
    <Layout>
      <Head>
        <title>NFT | Dino Pixel</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='bg-neutral-800 py-48 text-white bg-[url(/images/bg.png)] relative bg-blend-darken bg-top bg-no-repeat bg-cover'>
        <div
          className='max-w-7xl mx-auto px-8 flex flex-col justify-between lg:flex-row'
          data-aos='fade-up'
        >
          <div>
            <div className='max-w-xl flex-col space-y-10'>
              <div className='flex-col space-y-8'>
                <h1 className='text-5xl text-white'>Dino Pixel</h1>
                <h2 className='text-4xl text-primary border-b-4 inline-block pb-2 border-b-primary'>
                  NFT Project
                </h2>
              </div>

              <div>
                <p>
                  Meet a collection of 1000+ amazing figures with different
                  attributes and styles!
                </p>
              </div>

              <div className='flex gap-4 flex-wrap'>
                <Anchor bg='bg-neutral-700' href='#'>
                  Join Discord <Discord />
                </Anchor>
                <Anchor bg='bg-primary' href='#'>
                  Shop on Opensea <ArrowRight />
                </Anchor>
              </div>
            </div>
          </div>

          <div className='flex' data-aos='fade-up'>
            <div className='wiggle z-10 bg-gradient-to-b from-cyan-900 to-neutral-900 w-60 p-4 relative rounded-md shadow-2xl translate-x-6 translate-y-14 -rotate-6 lg:translate-y-7'>
              <Image src='/images/blue-dino.png' width={300} height={300} />
              <div className='bg-neutral-900 absolute w-full left-0 h-14 lg:h-28 bottom-0 rounded-b-md flex justify-center items-center'>
                <span>1.48 ETH</span>
              </div>
            </div>

            <div className='bg-gradient-to-b from-orange-600 to-pink-700 w-60 p-4 relative rounded-md shadow-2xl rotate-12 translate-y-24 -translate-x-6 lg:-translate-x-12 lg:-translate-y-8'>
              <Image src='/images/yellow-dino.png' width={300} height={300} />
              <div className='bg-neutral-900 absolute w-full left-0 h-14 lg:h-28 bottom-0 rounded-b-md flex justify-center items-center'>
                <span>1.23 ETH</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      <section className='w-full py-4 bg-neutral-900/40 px-7'>
        <div className='max-w-7xl mx-auto' data-aos='fade-up'>
          <Heading>Gallery</Heading>
          <div className='py-9'>
            <Swiper
              effect={'coverflow'}
              grabCursor={true}
              breakpoints={{
                0: {
                  slidesPerView: 1
                },
                468: {
                  slidesPerView: 2
                },
                768: {
                  slidesPerView: 3
                }
              }}
              autoplay={{
                delay: 2500,
                disableOnInteraction: false
              }}
              centeredSlides={false}
              coverflowEffect={{
                rotate: 50,
                stretch: 0,
                depth: 100,
                modifier: 1,
                slideShadows: false
              }}
              pagination={true}
              modules={[EffectCoverflow, Pagination, Autoplay]}
            >
              <SwiperSlide className='my-7 flex justify-center pb-4'>
                <div className='w-96 p-4 hover:scale-125 hover:rotate-12 duration-200'>
                  <Image src='/images/blue-dino.png' width={200} height={200} />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 hover:scale-125 hover:rotate-12 duration-200 '>
                  <Image
                    src='/images/yellow-dino.png'
                    width={200}
                    height={200}
                  />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 hover:scale-125 hover:rotate-12 duration-200'>
                  <Image
                    src='/images/green-dino.png'
                    width={200}
                    height={200}
                  />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 hover:scale-125 hover:rotate-12 duration-200 '>
                  <Image
                    className=''
                    src='/images/pink-dino.png'
                    width={200}
                    height={200}
                  />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 hover:scale-125 hover:rotate-12 duration-200 lg:-translate-y-8 lg:-translate-x-14'>
                  <Image
                    src='/images/purple-dino.png'
                    width={300}
                    height={300}
                  />
                </div>
              </SwiperSlide>
            </Swiper>
          </div>
        </div>
      </section>

      <section className='w-full py-4 bg-neutral-900/40 text-aliceBlue px-7'>
        <div className='flex-col-reverse lg:justify-between lg:flex-row max-w-7xl mx-auto flex items-center px-4 py-14 bg-[url(/images/background.png)]'>
          <div className='lg:w-4/6 flex-col space-y-6' data-aos='fade-right'>
            <Heading>1000+ Figures Collection</Heading>
            <p className='max-w-xl'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Vestibulum venenatis mauris in est laoreet, in lobortis diam
              lobortis.
            </p>
          </div>
          <div className='w-44 lg:w-72' data-aos='fade-left'>
            <Image src='/images/coin.png' width={300} height={300} />
          </div>
        </div>
      </section>

      <section className='w-full py-4 bg-neutral-900/40 text-aliceBlue px-7'>
        <div className='flex-col-reverse max-w-7xl mx-auto lg:gap-56 lg:flex-row-reverse flex items-center px-4 py-14'>
          <div
            className='flex-col space-y-6 justify-end items-end'
            data-aos='fade-up'
          >
            <Heading>Unique Attributes</Heading>
            <p className='max-w-xl block'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </div>
          <div className='w-44 lg:w-72' data-aos='fade-down'>
            <Image src='/images/atb.png' width={400} height={400} />
          </div>
        </div>
      </section>

      <section className='w-full py-4 bg-neutral-900/40 text-aliceBlue px-7'>
        <div className='max-w-7xl mx-auto gap-56 flex-col items-center px-4 py-14'>
          <Heading>Roadmap</Heading>
          <div className='flex flex-col gap-14 py-6 relative'>
            <div data-aos='fade-down'>
              <Box
                title='20% ETH Donation'
                number={1}
                description='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit'
              />
            </div>
            <div data-aos='fade-down'>
              <Box
                title='Sending ETH to other projects'
                number={2}
                description='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit'
              />
            </div>
            <div data-aos='fade-down' data-aos-duration='2300'>
              <Box
                title='All NFTs Sold'
                number={3}
                description='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit'
              />
            </div>
          </div>
        </div>
      </section>

      <section className='w-full py-4 bg-neutral-900/20 text-aliceBlue px-7'>
        <div className='max-w-7xl mx-auto gap-56 items-center px-4 py-14'>
          <div className='flex flex-col gap-8'>
            <Accordion
              title='What is Dino Pixel?'
              description='Dino Pixel is a collection of 1000+ amazing figures with different attributes and styles hosted on Ethereum Blockchain. You can buy these figures on OpenSea.'
            />
            <Accordion
              title='Hou much do they Cost?'
              description='Dino Pixel is a collection of 1000+ amazing figures with different attributes and styles hosted on Ethereum Blockchain. You can buy these figures on OpenSea.'
            />
            <Accordion
              title='Can i buy an NFT from Opensea?'
              description='Dino Pixel is a collection of 1000+ amazing figures with different attributes and styles hosted on Ethereum Blockchain. You can buy these figures on OpenSea.'
            />
          </div>
        </div>
      </section>
    </Layout>
  )
}
