import Anchor from 'components/Anchor'
import Layout from 'components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import { ArrowRight, Discord } from 'react-bootstrap-icons'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import 'swiper/css/effect-coverflow'
import 'swiper/css/autoplay'
import { Autoplay, EffectCoverflow, Pagination } from 'swiper'
import Heading from 'components/Heading'
import Box from 'components/Box'
import Aos from 'aos'
import { useEffect } from 'react'
import 'aos/dist/aos.css'
import Accordion from 'components/Accordion'
import ReactGA from 'react-ga'

const useAnalyticsEventTracker = (category = 'Dino') => {
  const eventTracker = (action = 'test action', label = 'test label') => {
    ReactGA.event({ category, action, label })
  }
  return eventTracker
}

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 1000, once: true })
  }, [])

  const gaEventTracker = useAnalyticsEventTracker('Open Sea')

  return (
    <Layout>
      <Head>
        <title>NFT | Dino Pixel</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='relative bg-neutral-800 bg-[url(/images/bg.png)] bg-cover bg-top bg-no-repeat py-48 text-white bg-blend-darken'>
        <div
          className='mx-auto flex max-w-7xl flex-col justify-between px-8 lg:flex-row'
          data-aos='fade-up'
        >
          <div>
            <div className='mx-auto max-w-xl flex-col space-y-10'>
              <div className='flex-col space-y-8'>
                <h1 className='text-5xl text-white'>Dino Pixel</h1>
                <h2 className='inline-block border-b-4 border-b-primary pb-2 text-4xl text-primary'>
                  NFT Project
                </h2>
              </div>

              <div>
                <p>
                  Meet a collection of 1000+ amazing figures with different
                  attributes and styles!
                </p>
              </div>

              <div className='flex flex-wrap gap-4'>
                <Anchor
                  bg='bg-neutral-700'
                  href='#'
                  onClick={() => gaEventTracker('call')}
                >
                  Join Discord <Discord />
                </Anchor>
                <Anchor bg='bg-primary' href='#'>
                  Shop on Opensea <ArrowRight />
                </Anchor>
              </div>
            </div>
          </div>

          <div className='flex lg:mx-0' data-aos='fade-up'>
            <div className='wiggle relative z-10 w-60 translate-x-6 translate-y-14 -rotate-6 rounded-md bg-gradient-to-b from-cyan-900 to-neutral-900 p-4 shadow-2xl lg:translate-y-7'>
              <Image src='/images/blue-dino.png' width={300} height={300} />
              <div className='absolute left-0 bottom-0 flex h-14 w-full items-center justify-center rounded-b-md bg-neutral-900 lg:h-28'>
                <span>1.48 ETH</span>
              </div>
            </div>

            <div className='relative w-60 translate-y-24 -translate-x-6 rotate-12 rounded-md bg-gradient-to-b from-orange-600 to-pink-700 p-4 shadow-2xl lg:-translate-x-12 lg:-translate-y-8'>
              <Image src='/images/yellow-dino.png' width={300} height={300} />
              <div className='absolute left-0 bottom-0 flex h-14 w-full items-center justify-center rounded-b-md bg-neutral-900 lg:h-28'>
                <span>1.23 ETH</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      <section id='gallery' className='w-full bg-neutral-900/40 py-4 px-7'>
        <div className='mx-auto max-w-7xl' data-aos='fade-up'>
          <Heading>Gallery</Heading>
          <div className='py-9'>
            <Swiper
              effect={'coverflow'}
              grabCursor={true}
              breakpoints={{
                0: {
                  slidesPerView: 1
                },
                468: {
                  slidesPerView: 2
                },
                768: {
                  slidesPerView: 3
                }
              }}
              autoplay={{
                delay: 2500,
                disableOnInteraction: false
              }}
              centeredSlides={false}
              coverflowEffect={{
                rotate: 50,
                stretch: 0,
                depth: 100,
                modifier: 1,
                slideShadows: false
              }}
              pagination={true}
              modules={[EffectCoverflow, Pagination, Autoplay]}
            >
              <SwiperSlide className='my-7 flex justify-center pb-4'>
                <div className='w-96 p-4 duration-200 hover:rotate-12 hover:scale-125'>
                  <Image src='/images/blue-dino.png' width={200} height={200} />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 duration-200 hover:rotate-12 hover:scale-125 '>
                  <Image
                    src='/images/yellow-dino.png'
                    width={200}
                    height={200}
                  />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 duration-200 hover:rotate-12 hover:scale-125'>
                  <Image
                    src='/images/green-dino.png'
                    width={200}
                    height={200}
                  />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 duration-200 hover:rotate-12 hover:scale-125 '>
                  <Image
                    className=''
                    src='/images/pink-dino.png'
                    width={200}
                    height={200}
                  />
                </div>
              </SwiperSlide>
              <SwiperSlide className='my-7 flex justify-center'>
                <div className='w-96 p-4 duration-200 hover:rotate-12 hover:scale-125 lg:-translate-y-8 lg:-translate-x-14'>
                  <Image
                    src='/images/purple-dino.png'
                    width={300}
                    height={300}
                  />
                </div>
              </SwiperSlide>
            </Swiper>
          </div>
        </div>
      </section>

      <section
        id='features'
        className='w-full bg-neutral-900/40 py-4 px-7 text-aliceBlue'
      >
        <div className='mx-auto flex max-w-7xl flex-col-reverse items-center bg-[url(/images/background.png)] px-4 py-14 lg:flex-row lg:justify-between'>
          <div className='flex-col space-y-6 lg:w-4/6' data-aos='fade-right'>
            <Heading>1000+ Figures Collection</Heading>
            <p className='max-w-xl'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Vestibulum venenatis mauris in est laoreet, in lobortis diam
              lobortis.
            </p>
          </div>
          <div className='w-44 lg:w-72' data-aos='fade-left'>
            <Image src='/images/coin.png' width={300} height={300} />
          </div>
        </div>
      </section>

      <section className='w-full bg-neutral-900/40 py-4 px-7 text-aliceBlue'>
        <div className='mx-auto flex max-w-7xl flex-col-reverse items-center px-4 py-14 lg:flex-row-reverse lg:gap-56'>
          <div
            className='flex-col items-end justify-end space-y-6'
            data-aos='fade-up'
          >
            <Heading>Unique Attributes</Heading>
            <p className='block max-w-xl'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </div>
          <div className='w-44 lg:w-72' data-aos='fade-down'>
            <Image src='/images/atb.png' width={400} height={400} />
          </div>
        </div>
      </section>

      <section
        id='roadmap'
        className='w-full bg-neutral-900/40 py-4 px-7 text-aliceBlue'
      >
        <div className='mx-auto max-w-7xl flex-col items-center gap-56 px-4 py-14'>
          <Heading>Roadmap</Heading>
          <div className='relative flex flex-col gap-14 py-6'>
            <div data-aos='fade-down'>
              <Box
                title='20% ETH Donation'
                number={1}
                description='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit'
              />
            </div>
            <div data-aos='fade-down'>
              <Box
                title='Sending ETH to other projects'
                number={2}
                description='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit'
              />
            </div>
            <div data-aos='fade-down' data-aos-duration='2300'>
              <Box
                title='All NFTs Sold'
                number={3}
                description='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit'
              />
            </div>
          </div>
        </div>
      </section>

      <section
        id='faq'
        className='w-full bg-neutral-900/20 py-4 px-7 text-aliceBlue'
      >
        <div className='mx-auto max-w-7xl items-center gap-56 px-4 py-14'>
          <Heading>Faq</Heading>
          <div className='flex flex-col gap-8'>
            <Accordion
              title='What is Dino Pixel?'
              description='Dino Pixel is a collection of 1000+ amazing figures with different attributes and styles hosted on Ethereum Blockchain. You can buy these figures on OpenSea.'
            />
            <Accordion
              title='Hou much do they Cost?'
              description='Dino Pixel is a collection of 1000+ amazing figures with different attributes and styles hosted on Ethereum Blockchain. You can buy these figures on OpenSea.'
            />
            <Accordion
              title='Can i buy an NFT from Opensea?'
              description='Dino Pixel is a collection of 1000+ amazing figures with different attributes and styles hosted on Ethereum Blockchain. You can buy these figures on OpenSea.'
            />
          </div>
        </div>
      </section>
    </Layout>
  )
}
